# Generated by Django 5.2.8 on 2025-12-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('image_type', models.CharField(choices=[('INFRARED_FULL', '적외선 (IR)'), ('VISIBLE_FULL', '가시광'), ('WATERVAPOR', '수증기')], default='INFRARED_FULL', max_length=20)),
                ('base_path', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '위성 영상 프레임',
                'verbose_name_plural': '위성 영상 프레임',
                'ordering': ['-timestamp'],
            },
        ),
    ]
