# Generated by Django 6.0 on 2025-12-21 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurementsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dischargetimeseries',
            new_name='measurement_station_417225_idx',
            old_name='measurement_station_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='measurementsession',
            new_name='measurement_user_id_47f5ca_idx',
            old_name='measurement_user_id_session_idx',
        ),
        migrations.RenameIndex(
            model_name='waterleveltimeseries',
            new_name='measurement_station_f8203d_idx',
            old_name='measurement_station_10833b_idx',
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='세션키'),
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
