# Generated by Django 6.0 on 2025-12-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_add_session_key_and_nullable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsession',
            name='setup_data',
            field=models.JSONField(default=dict, verbose_name='추가 설정'),
        ),
    ]
