# Generated by Django 6.0 on 2025-12-21 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_add_setup_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50, verbose_name='유속계 번호')),
                ('meter_type', models.CharField(choices=[('propeller', '프로펠러형'), ('electronic', '전자식')], default='propeller', max_length=20, verbose_name='종류')),
                ('coef_a', models.FloatField(default=0.0, verbose_name='시동유속 a (m/s)')),
                ('coef_b', models.FloatField(default=1.0, verbose_name='검정상수 b')),
                ('range_min', models.FloatField(default=0.0, verbose_name='최소 유속 (m/s)')),
                ('range_max', models.FloatField(default=6.0, verbose_name='최대 유속 (m/s)')),
                ('uncertainty', models.FloatField(default=1.0, verbose_name='검정 불확실도 (%)')),
                ('calibration_date', models.DateField(blank=True, null=True, verbose_name='검정일')),
                ('calibration_org', models.CharField(blank=True, max_length=100, verbose_name='검정기관')),
                ('status', models.CharField(choices=[('valid', '유효'), ('expiring', '만료 임박'), ('expired', '만료')], default='valid', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '유속계',
                'verbose_name_plural': '유속계',
                'ordering': ['-created_at'],
            },
        ),
    ]
