# Generated by Django 6.0 on 2025-12-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_add_meter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='calibration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='검정 유효기간'),
        ),
    ]
