# Generated by Django 6.0 on 2025-12-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_add_calibration_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementsession',
            name='hydraulic_radius',
            field=models.FloatField(blank=True, null=True, verbose_name='동수반경(m)'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='mean_velocity',
            field=models.FloatField(blank=True, null=True, verbose_name='평균유속(m/s)'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='quality_grade',
            field=models.CharField(blank=True, max_length=5, verbose_name='등급'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='stage',
            field=models.FloatField(blank=True, null=True, verbose_name='수위(m)'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='uncertainty',
            field=models.FloatField(blank=True, null=True, verbose_name='불확실도(%)'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='velocity_verticals',
            field=models.IntegerField(blank=True, null=True, verbose_name='유속측선수'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='wetted_perimeter',
            field=models.FloatField(blank=True, null=True, verbose_name='윤변(m)'),
        ),
    ]
